export const GET_DETAIL_PURCHASE_ORDER = "GET_DETAIL_PURCHASE_ORDER"
export const GET_DETAIL_PURCHASE_ORDER_SUCCESS = "GET_DETAIL_PURCHASE_ORDER_SUCCESS"
export const GET_DETAIL_PURCHASE_ORDER_ERROR = "GET_DETAIL_PURCHASE_ORDER_ERROR"

export const CONFIRM_PURCHASE_ORDER_REQUEST = "CONFIRM_PURCHASE_ORDER_REQUEST"
export const CONFIRM_PURCHASE_ORDER_SUCCESS = "CONFIRM_PURCHASE_ORDER_SUCCESS"
export const CONFIRM_PURCHASE_ORDER_ERROR = "CONFIRM_PURCHASE_ORDER_ERROR"

export const CREATE_PRICE_QUOTE_REQUEST = "CREATE_PRICE_QUOTE_REQUEST"
export const CREATE_PRICE_QUOTE_SUCCESS = "CREATE_PRICE_QUOTE_SUCCESS"
export const CREATE_PRICE_QUOTE_ERROR = "CREATE_PRICE_QUOTE_ERROR"

export const CREATE_PURCHASE_ORDER_REQUEST = "CREATE_PURCHASE_ORDER_REQUEST"
export const CREATE_PURCHASE_ORDER_SUCCESS = "CREATE_PURCHASE_ORDER_SUCCESS"
export const CREATE_PURCHASE_ORDER_ERROR = "CREATE_PURCHASE_ORDER_ERROR"

export const SEND_CONFIRM_PURCHASE_ORDER_REQUEST = "SEND_CONFIRM_PURCHASE_ORDER_REQUEST"
export const SEND_CONFIRM_PURCHASE_ORDER_SUCCESS = "SEND_CONFIRM_PURCHASE_ORDER_SUCCESS"
export const SEND_CONFIRM_PURCHASE_ORDER_ERROR = "SEND_CONFIRM_PURCHASE_ORDER_ERROR"

export const SAVE_PRODUCTS_PURCHASE_ORDER_REQUEST = "SAVE_PRODUCTS_PURCHASE_ORDER_REQUEST"
export const SAVE_PRODUCTS_PURCHASE_ORDER_SUCCESS = "SAVE_PRODUCTS_PURCHASE_ORDER_SUCCESS"
export const SAVE_PRODUCTS_PURCHASE_ORDER_ERROR = "SAVE_PRODUCTS_PURCHASE_ORDER_ERROR"


// export const SEND_MAIL_PURCHASE_ORDER="SEND_MAIL_PURCHASE_ORDER"

export const SEND_MAIL_SERVICE_REQUEST ="SEND_MAIL_SERVICE_REQUEST"
export const SEND_MAIL_SERVICE_SUCCESS ="SEND_MAIL_SERVICE_SUCCESS"
export const SEND_MAIL_SERVICE_ERROR ="SEND_MAIL_SERVICE_ERROR"

// export const GET_PRODUCT_PURCHASE_ORDER="GET_PRODUCT_PURCHASE_ORDER"
// export const GET_PRODUCT_PURCHASE_ORDER_SUCCESS="GET_PRODUCT_PURCHASE_ORDER_SUCCESS"
// export const GET_PRODUCT_PURCHASE_ORDER_ERROR="GET_PRODUCT_PURCHASE_ORDER_ERROR"

export const SET_DEFAULT_PRODUCT_PURCHASE_ORDER="SET_DEFAULT_PRODUCT_PURCHASE_ORDER"

export const REJECT_PURCHASE_ORDER_CONFIRM_REQUEST="REJECT_PURCHASE_ORDER_CONFIRM_REQUEST"
export const REJECT_PURCHASE_ORDER_CONFIRM_SUCCESS="REJECT_PURCHASE_ORDER_CONFIRM_SUCCESS"
export const REJECT_PURCHASE_ORDER_CONFIRM_ERROR="REJECT_PURCHASE_ORDER_CONFIRM_ERROR"

export const EDIT_PRICE_QUOTE_REQUEST="EDIT_PRICE_QUOTE_REQUEST"
export const EDIT_PRICE_QUOTE_SUCCESS="EDIT_PRICE_QUOTE_SUCCESS"
export const EDIT_PRICE_QUOTE_ERROR="EDIT_PRICE_QUOTE_ERROR"
