export const GET_ALL_GOOD_ISSUE_REQUEST = 'GET_ALL_GOOD_ISSUE_REQUEST'
export const GET_ALL_GOOD_ISSUE_RESPONSE = 'GET_ALL_GOOD_ISSUE_RESPONSE'
export const GET_ALL_GOOD_ISSUE_ERROR = 'GET_ALL_GOOD_ISSUE_ERROR'
