export const GET_ALL_GOOD_ISSUE_REQUESTING = "GET_ALL_GOOD_ISSUE_REQUESTING"
export const GET_ALL_GOOD_ISSUE_SUCCESS = "GET_ALL_GOOD_ISSUE_SUCCESS"
export const GET_ALL_GOOD_ISSUE_ERROR = "GET_ALL_GOOD_ISSUE_ERROR"