export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST'
export const GET_LOCATION_RESPONSE = 'GET_LOCATION_RESPONSE'
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR'

export const CREATE_STOCKTAKE_REQUEST = 'CREATE_STOCKTAKE_REQUEST'
export const CREATE_STOCKTAKE_RESPONSE = 'CREATE_sTOCKTAKE_RESPONSE'
export const CREATE_STOCKTAKE_ERROR = 'CREATE_sTOCKTAKE_ERROR'

export const GET_PACKAGE_REQUEST = 'GET_PACKAGE_REQUEST'
export const GET_PACKAGE_RESPONSE = 'GET_PACKAGE_RESPONSE'
export const GET_PACKAGE_ERROR = 'GET_PACKAGE_ERROR'
