export const CREATE_GOODISSUE_REQUEST = 'CREATE_GOODISSUE_REQUEST'
export const CREATE_GOODISSUE_RESPONSE = 'CREATE_GOODISSUE_RESPONSE'
export const CREATE_GOODISSUE_ERROR = 'CREATE_GOODISSUE_ERROR'

export const ADD_GOODISSUE_REQUEST = 'ADD_GOODISSUE_REQUEST'
export const ADD_GOODISSUE_RESPONSE = 'ADD_GOODISSUE_RESPONSE'
export const ADD_GOODISSUE_ERROR = 'ADD_GOODISSUE_ERROR'

export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST'
export const GET_LOCATION_RESPONSE = 'GET_LOCATION_RESPONSE'
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR'