export const GET_DETAIL_QUOTE_PRODUCT_REQUESTING = "GET_DETAIL_QUOTE_PRODUCT_REQUESTING"
export const GET_DETAIL_QUOTE_PRODUCT_SUCCESS = "GET_DETAIL_QUOTE_PRODUCT_SUCCESS"
export const GET_DETAIL_QUOTE_PRODUCT_ERROR = "GET_DETAIL_QUOTE_PRODUCT_ERROR"
// export const UPDATE = "GET_DETAIL_QUOTE_PRODUCT_ERROR"

