export const GET_ALL_NOTIFICATIONS_REQUEST = "GET_ALL_NOTIFICATIONS_REQUEST"
export const GET_ALL_NOTIFICATIONS_RESPONSE = "GET_ALL_NOTIFICATIONS_RESPONSE"
export const GET_ALL_NOTIFICATIONS_ERROR = "GET_ALL_NOTIFICATIONS_ERROR"