export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_RESPONSE = "GET_ALL_PRODUCTS_RESPONSE";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_RESPONSE = "GET_ALL_CATEGORY_RESPONSE";
export const GET_ALL_CATEGORY_ERROR = "GET_ALL_CATEGORY_ERROR";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_RESPONSE = "CREATE_CATEGORY_RESPONSE";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_RESPONSE = "UPDATE_CATEGORY_RESPONSE";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";

export const DEACTIVE_CATEGORY_REQUEST = "DEACTIVE_CATEGORY_REQUEST";
export const DEACTIVE_CATEGORY_RESPONSE = "DEACTIVE_CATEGORY_RESPONSE";
export const DEACTIVE_CATEGORY_ERROR = "DEACTIVE_CATEGORY_ERROR";

export const GET_ALL_LOCATIONS_REQUEST = "GET_ALL_LOCATIONS_REQUEST";
export const GET_ALL_LOCATIONS_RESPONSE = "GET_ALL_LOCATIONS_RESPONSE";
export const GET_ALL_LOCATIONS_ERROR = "GET_ALL_LOCATIONS_ERROR";

export const GET_ALL_VARIANTS_REQUEST = "GET_ALL_VARIANTS_REQUEST";
export const GET_ALL_VARIANTS_ERROR = "GET_ALL_LOCATIONS_ERROR";
export const GET_ALL_VARIANTS_RESPONSE = "GET_ALL_VARIANTS_RESPONSE";

export const CREATE_LOCATION_REQUEST = "CREATE_LOCATION_REQUEST";
export const CREATE_LOCATION_ERROR = "CREATE_LOCATION_ERROR";
export const CREATE_LOCATION_RESPONSE = "CREATE_LOCATION_RESPONSE";

export const UPDATE_LOCATION_REQUEST = "UPDATE_LOCATION_REQUEST";
export const UPDATE_LOCATION_ERROR = "UPDATE_LOCATION_ERROR";
export const UPDATE_LOCATION_RESPONSE = "UPDATE_LOCATION_RESPONSE";

export const GET_ALL_UPDATES_REQUEST = "GET_ALL_UPDATES_REQUEST";
export const GET_ALL_UPDATES_RESPONSE = "GET_ALL_UPDATES_RESPONSE";
export const GET_ALL_UPDATES_ERROR = "GET_ALL_UPDATES_ERROR";


export const AGREE_UPDATE_SKU_REQUEST = " AGREE_UPDATE_SKU_REQUEST"
export const AGREE_UPDATE_SKU_RESPONSE = "AGREE_UPDATE_SKU_RESPONSE"
export const AGREE_UPDATE_SKU_ERR = "AGREE_UPDATE_SKU_ERR"

export const REJECT_UPDATE_SKU_REQUEST = "REJECT_UPDATE_SKU_REQUEST"
export const REJECT_UPDATE_SKU_RESPONSE = "REJECT_UPDATE_SKU_RESPONSE"
export const REJECT_UPDATE_SKU_ERR = "REJECT_UPDATE_SKU_ERR"

export const RESET = "RESET";
