// export const GET_DETAIL_COMPANY_REQUESTING = "GET_DETAIL_COMPANY_REQUESTING"
// export const GET_DETAIL_COMPANY_SUCCESS = "GET_DETAIL_COMPANY_SUCCESS"
// export const GET_DETAIL_COMPANY_ERROR = "GET_DETAIL_COMPANY_ERROR"
// export const GET_DETAIL_COMPANY_CLEAN = "GET_DETAIL_COMPANY_CLEAN"

export const UPDATE_COMPANY_REQUESTING = "UPDATE_COMPANY_REQUESTING"
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS"
export const UPDATE_COMPANY_ERROR = "UPDATE_COMPANY_ERROR"
export const UPDATE_COMPANY_CLEAN = "UPDATE_COMPANY_CLEAN"

export const UPDATE_IMAGE_COMPANY_REQUESTING = "UPDATE_IMAGE_COMPANY_REQUESTING"
export const UPDATE_IMAGE_COMPANY_SUCCESS = "UPDATE_IMAGE_COMPANY_SUCCESS"
export const UPDATE_IMAGE_COMPANY_ERROR = "UPDATE_IMAGE_COMPANY_ERROR"
export const UPDATE_IMAGE_COMPANY_CLEAN = "UPDATE_IMAGE_COMPANY_CLEAN"
