export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'  
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'  
export const LOGIN_ERROR = 'LOGIN_ERROR' 
export const LOGIN_BANNED = 'LOGIN_BANNED' 
export const LOGIN_CLEAN = 'LOGIN_CLEAN' 

export const LOGOUT_REQUESTING = 'LOGOUT_REQUESTING'  
export const LOGUT_SUCCESS = 'LOGUT_SUCCESS'  
export const LOGOUT_ERROR = 'LOGOUT_ERROR' 
