export const GET_ALL_ROLE_REQUEST = 'GET_ALL_ROLE_REQUEST'
export const GET_ALL_ROLE_RESPONSE = 'GET_ALL_ROLE_RESPONSE'
//error
export const GET_ALL_ROLE_ERROR = 'GET_ALL_ROLE_ERROR'

//get all account
export const GET_ALL_ACCOUNT_REQUEST = 'GET_ALL_ACCOUNT_REQUEST'
export const GET_ALL_ACCOUNT_RESPONSE = 'GET_ALL_ACCOUNT_RESPONSE'

//error
export const GET_ALL_ACCOUNT_ERROR = 'GET_ALL_ACCOUNT_ERROR'