export const GET_GR_DETAILS_REQUEST = 'GET_GR_DETAILS_REQUEST';
export const GET_GR_DETAILS_RESPONSE = 'GET_GR_DETAILS_RESPONSE'
export const GET_GR_DETAILS_ERROR = 'GET_GR_DETAILS_ERROR'

export const RESET = 'RESET'