export const CREATE_PR_REQUEST = "CREATE_PR_REQUEST";
export const CREATE_PR_RESPONSE = "CREATE_PR_RESPONSE";
export const CREATE_PR_ERROR = "CREATE_PR_ERROR";

export const GET_ALL_SUPPLIER_REQUEST = "GET_ALL_SUPPLIER_REQUEST";
export const GET_ALL_SUPPLIER_RESPONSE = "GET_ALL_SUPPLIER_RESPONSE"
export const GET_ALL_SUPPLIER_ERROR = "GET_ALL_SUPPLIER_ERROR"

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
