export const CREAT_SUPPLIER_REQUEST = "CREAT_SUPPLIER_REQUEST";
export const CREAT_SUPPLIER_RESPONSE = "CREAT_SUPPLIER_RESPONSE";
export const CREAT_SUPPLIER_ERROR = "CREAT_SUPPLIER_ERROR";

export const RESET = "RESET";
