export const GET_VALUE_DASHBOARD_REQUESTING = "GET_VALUE_DASHBOARD_REQUESTING"
export const GET_VALUE_DASHBOARD_SUCCESS = "GET_VALUE_DASHBOARD_SUCCESS"
export const GET_VALUE_DASHBOARD_ERROR = "GET_VALUE_DASHBOARD_ERROR"