export const UPDATE_PROFILE_REQUESTING = 'UPDATE_PROFILE_REQUESTING'  
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'  
export const UPDATE_PROFILE_ERROR= 'UPDATE_PROFILE_ERROR'  
export const CLEAER_UPDATE_PROFILE= 'CLEAER_UPDATE_PROFILE'  