export const GET_DETAILS_PR_REQUEST = "GET_DETAILS_PR_REQUEST";
export const GET_DETAILS_PR_RESPONSE = "GET_DETAILS_PR_RESPON";
export const GET_DETAILS_PR_ERROR = "GET_DETAILS_PR_ERROR";

export const SUBMIT_REQUEST = "SUBMIT_REQUEST";
export const SUBMIT_RESPONSE = "SUBMIT_RESPONSE";
export const SUBMIT_ERROR = "SUBMIT_ERROR";

export const UPDATE_PR_REQUEST= "UPDATE_PR_REQUEST";
export const UPDATE_PR_RESPONSE = "UPDATE_PR_RESPONSE";
export const UPDATE_PR_ERROR = "UPDATE_PR_ERROR";

export const DELETE_PR_REQUEST = "DELETE_PR_REQUEST"
export const DELETE_PR_RESPONSE = "DELETE_PR_RESPONSE"
export const DELETE_PR_ERROR = "DELETE_PR_ERROR"

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";