export const GET_DETAILS_PR_REQUEST = "GET_DETAILS_PR_REQUEST";
export const GET_DETAILS_PR_RESPONSE = "GET_DETAILS_PR_RESPON";
export const GET_DETAILS_PR_ERROR = "GET_DETAILS_PR_ERROR";

export const SUBMIT_REQUEST = "SUBMIT_REQUEST";
export const SUBMIT_RESPONSE = "SUBMIT_RESPONSE";
export const SUBMIT_ERROR = "SUBMIT_ERROR";
