export const SEARCH_PURCHASE_ORDER = "SEARCH_PURCHASE_ORDER"
export const SEARCH_PURCHASE_ORDER_ERROR = "SEARCH_PURCHASE_ORDER_ERROR"
export const SEARCH_PURCHASE_ORDER_SEARCH = "SEARCH_PURCHASE_ORDER_SEARCH"
export const GET_PRICE_QUOTE_REQUESTING = "GET_PRICE_QUOTE_REQUESTING"
export const GET_PRICE_QUOTE_SUCCESS = "GET_PRICE_QUOTE_SUCCESS"
export const GET_PRICE_QUOTE_ERROR = "GET_PRICE_QUOTE_ERROR"


