export const CREATE_ROLE_REQUESTING  = "CREATE_ROLE_REQUESTING"
export const CREATE_ROLE_SUCCESS  = "CREATE_ROLE_SUCCESS"
export const CREATE_ROLE_ERROR  = "CREATE_ROLE_ERROR"

export const GET_DETAIL_ROLE_REQUESTING  = "GET_DETAIL_ROLE_REQUESTING"
export const GET_DETAIL_ROLE_SUCCESS  = "GET_DETAIL_ROLE_SUCCESS"
export const GET_DETAIL_ROLE_ERROR  = "GET_DETAIL_ROLE_ERROR"

export const UPDATE_DETAIL_ROLE_REQUESTING  = "UPDATE_DETAIL_ROLE_REQUESTING"
export const UPDATE_DETAIL_ROLE_SUCCESS  = "UPDATE_DETAIL_ROLE_SUCCESS"
export const UPDATE_DETAIL_ROLE_ERROR  = "UPDATE_DETAIL_ROLE_ERROR"