export const CREATE_ACC_REQUEST = "CREATE_ACC_REQUEST"
export const CREATE_ACC_RESPONSE = "CREATE_ACC_RESPONSE"
export const CREATE_ACC_ERR = "CREATE_ACC_ERR"

export const GET_DETAIL_ACC_REQUEST = "GET_DETAIL_ACC_REQUEST"
export const GET_DETAIL_ACC_SUCCESS = "GET_DETAIL_ACC_SUCCESS"
export const GET_DETAIL_ACC_ERR = "GET_DETAIL_ACC_ERR"

export const UPDATE_DETAIL_ACC_REQUEST = "UPDATE_DETAIL_ACC_REQUEST"
export const UPDATE_DETAIL_ACC_SUCCESS = "UPDATE_DETAIL_ACC_SUCCESS"
export const UPDATE_DETAIL_ACC_ERR = "UPDATE_DETAIL_ACC_ERR"

export const BAN_DETAIL_ACC_REQUEST = "BAN_DETAIL_ACC_REQUEST"
export const BAN_DETAIL_ACC_SUCCESS = "BAN_DETAIL_ACC_SUCCESS"
export const BAN_DETAIL_ACC_ERR = "BAN_DETAIL_ACC_ERR"