export const SEARCH_GOODS_RECEIPT_ERROR = "SEARCH_GOODS_RECEIPT_ERROR";
export const SEARCH_GOODS_RECEIPT = "SEARCH_GOODS_RECEIPT";
//export const SEARCH_GOODS_RECEIPT_LIST = "SEARCH_GOODS_RECEIPT_RESULT";
