export const GET_DETAILS_PRODUCT_REQUEST = "GET_DETAILS_PRODUCT_REQUEST";
export const GET_DETAILS_PRODUCT_RESPONSE = "GET_DETAILS_PRODUCT_RESPONSE";
export const GET_DETAILS_PRODUCT_ERROR = "GET_DETAILS_PRODUCT_ERROR";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_RESPONSE = "UPDATE_PRODUCT_RESPONSE";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

export const GET_DETAILS_VARIANT_REQUEST = "GET_DETAILS_VARIANT_REQUEST";
export const GET_DETAILS_VARIANT_RESPONSE = "GET_DETAILS_VARIANT_RESPONSE";
export const GET_DETAILS_VARIANT_ERROR = "GET_DETAILS_VARIANT_ERROR";

export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_RESPONSE = "GET_BRAND_RESPONSE";
export const GET_BRAND_ERROR = "GET_BRAND_ERROR";
