export const GET_GOOD_ISSUE_DETAIL_REQUEST = "GET_GOOD_ISSUE_DETAIL_REQUEST"
export const GET_GOOD_ISSUE_DETAIL_SUCCESS = "GET_GOOD_ISSUE_DETAIL_SUCCESS"
export const GET_GOOD_ISSUE_DETAIL_ERROR = "GET_GOOD_ISSUE_DETAIL_ERROR"

export const CREATE_GOOD_ISSUEL_REQUEST = "CREATE_GOOD_ISSUEL_REQUEST"
export const CREATE_GOOD_ISSUE_SUCCESS = "CREATE_GOOD_ISSUE_SUCCESS"
export const CREATE_GOOD_ISSUE_ERROR = "CREATE_GOOD_ISSUE_ERROR"

export const UPDATE_GOOD_ISSUEL_REQUEST = "UPDATE_GOOD_ISSUEL_REQUEST"
export const UPDATE_GOOD_ISSUE_SUCCESS = "UPDATE_GOOD_ISSUE_SUCCESS"
export const UPDATE_GOOD_ISSUE_ERROR = "UPDATE_GOOD_ISSUE_ERROR"