export const GET_ALL_STOCKTAKE_REQUEST = "GET_ALL_STOCKTAKE_REQUEST";
export const GET_ALL_STOCKTAKE_RESPONSE = "GET_ALL_STOCKTAKE_RESPONSE";
export const GET_ALL_STOCKTAKE_ERROR = "GET_ALL_STOCKTAKE_ERROR";
