export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_RESPONSE = "GET_ALL_PRODUCTS_RESPONSE";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_RESPONSE = "GET_ALL_CATEGORY_RESPONSE";
export const GET_ALL_CATEGORY_ERROR = "GET_ALL_CATEGORY_ERROR";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_RESPONSE = "CREATE_CATEGORY_RESPONSE";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_ERROR";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_RESPONSE = "UPDATE_CATEGORY_RESPONSE";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";

export const DEACTIVE_CATEGORY_REQUEST = "DEACTIVE_CATEGORY_REQUEST";
export const DEACTIVE_CATEGORY_RESPONSE = "DEACTIVE_CATEGORY_RESPONSE";
export const DEACTIVE_CATEGORY_ERROR = "DEACTIVE_CATEGORY_ERROR";
