export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_RESPONSE = 'GET_ALL_PRODUCTS_RESPONSE'
export const GET_ALL_PRODUCTS_ERROR = 'GET_ALL_PRODUCTS_ERROR'

export const GET_ALL_CATEGORY_REQUEST = 'GET_ALL_CATEGORY_REQUEST'
export const GET_ALL_CATEGORY_RESPONSE = 'GET_ALL_CATEGORY_RESPONSE'
export const GET_ALL_CATEGORY_ERROR = 'GET_ALL_CATEGORY_ERROR'

