export const GET_DETAILS_STOCKTAKE_REQUEST = 'GET_DETAILS_STOCKTAKE_REQUEST'
export const GET_DETAILS_STOCKTAKE_RESPONSE = 'GET_DETAILS_STOCKTAKE_RESPONSE'
export const GET_DETAILS_STOCKTAKE_ERROR = 'GET_DETAILS_STOCKTAKE_ERROR'