export const GET_DETAILS_STOCKTAKE_REQUEST = "GET_DETAILS_STOCKTAKE_REQUEST";
export const GET_DETAILS_STOCKTAKE_RESPONSE = "GET_DETAILS_STOCKTAKE_RESPONSE";
export const GET_DETAILS_STOCKTAKE_ERROR = "GET_DETAILS_STOCKTAKE_ERROR";

export const REJECT_STOCKTAKE_REQUEST = "REJECT_STOCKTAKE_REQUEST";
export const REJECT_STOCKTAKE_RESPONSE = "REJECT_STOCKTAKE_RESPONSE";
export const REJECT_STOCKTAKE_ERROR = "REJECT_STOCKTAKE_ERROR";

export const SUBMIT_REQUEST = "SUBMIT_REQUEST";
export const SUBMIT_RESPONSE = "SUBMIT_RESPONSE";
export const SUBMIT_ERROR = "SUBMIT_ERROR";

export const ADJUST_REQUEST = "ADJUST_REQUEST";
export const ADJUST_RESPONSE = "ADJUST_RESPONSE";
export const ADJUST_ERROR = "ADJUST_ERROR";

export const UPDATE_STOCKTAKE_REQUEST = "UPDATE_STOCKTAKE_REQUEST"
export const UPDATE_STOCKTAKE_RESPONSE = "UPDATE_STOCKTAKE_RESPONSE"
export const UPDATE_STOCKTAKE_ERROR = "UPDATE_STOCKTACKE_ERROR"

export const RESET = "RESET";