// export const CLICK_QUOTE_ORDER = "CLICK_QUOTE_ORDER"
// export const CLICK_CREATE_PRICE_QUOTE_REQUEST= "CLICK_CREATE_PRICE_QUOTE_REQUEST"
// export const CLICK_TO_SEND_MAIL_PRICE_QUOTE= "CLICK_TO_SEND_MAIL_PRICE_QUOTE"
// export const CLICK_TO_PREVIEW_PRICE_QUOTE= "CLICK_TO_PREVIEW_PRICE_QUOTE"
