//
export const GET_CONFIRMED_PURCHASE_ORDER_REQUEST =
  "GET_CONFIRMED_PURCHASE_ORDER_REQUEST";
export const GET_CONFIRMED_PURCHASE_ORDER_RESPONSE =
  "GET_CONFIRMED_PURCHASE_ORDER_RESPONSE";

//error
export const GET_CONFIRMED_PURCHASE_ORDER_ERROR =
  "GET_CONFIRMED_PURCHASE_ORDER_ERROR";

//
export const GET_DETAILS_PO_REQUEST = "GET_DETAILS_PO_REQUEST";
export const GET_DETAILS_PO_RESPONSE = "GET_DETAILS_PO_RESPONSE";

//error
export const GET_DETAILS_PO_ERROR = "GET_DETAILS_PO_ERROR";

//
export const SEND_CREATING_GOODS_RECEIPT_REQUEST =
  "SEND_CREATING_GOODS_RECEIPT_REQUEST";
export const SEND_CREATING_GOODS_RECEIPT_RESPONSE =
  "SEND_CREATING_GOODS_RECEIPT_RESPONSE";

//error
export const SEND_CREATING_GOODS_RECEIPT_ERROR =
  "SEND_CREATING_GOODS_RECEIPT_ERROR";

//location
export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST";
export const GET_LOCATION_RESPONSE = "GET_LOCATION_RESPONSE";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";
//check duplicate
export const CHECK_DUPLICATE_REQUEST = "CHECK_DUPLICATE_REQUEST";
export const CHECK_DUPLICATE_RESPONSE = "CHECK_DUPLICATE_RESPONSE";
export const CHECK_DUPLICATE_ERROR = "CHECK_DUPLICATE_ERROR";

export const CHECK_SKUEXISTS_REQUEST = "CHECK_SKUEXISTS_REQUEST";
export const CHECK_SKUEXISTS_RESPONSE = "CHECK_SKUEXISTS_RESPONSE";
export const CHECK_SKUEXISTS_ERROR = "CHECK_SKUEXISTS_ERROR";

export const RESET = "RESET";
