//
export const GET_CONFIRMED_PURCHASE_ORDER_REQUEST = "GET_CONFIRMED_PURCHASE_ORDER_REQUEST";
export const GET_CONFIRMED_PURCHASE_ORDER_RESPONSE = "GET_CONFIRMED_PURCHASE_ORDER_RESPONSE";

//error
export const GET_CONFIRMED_PURCHASE_ORDER_ERROR = "GET_CONFIRMED_PURCHASE_ORDER_ERROR";


//
export const GET_DETAILS_PO_REQUEST = "GET_DETAILS_PO_REQUEST";
export const GET_DETAILS_PO_RESPONSE = "GET_DETAILS_PO_RESPONSE";

//error
export const GET_DETAILS_PO_ERROR = "GET_DETAILS_PO_ERROR";