export const GET_DETAILS_SUPPLIER_REQUEST = "GET_DETAILS_SUPPLIER_REQUEST";
export const GET_DETAILS_SUPPLIER_RESPONSE = "GET_DETAILS_SUPPLIER_RESPONSE";
export const GET_DETAILS_SUPPLIER_ERROR = "GET_DETAILS_SUPPLIER_ERROR";

export const UPDATE_SUPPLIER_REQUEST = "UPDATE_SUPPLIER_REQUEST";
export const UPDATE_SUPPLIER_RESPONSE = "UPDATE_SUPPLIER_RESPONSE";
export const UPDATE_SUPPLIER_ERROR = "UPDATE_SUPPLIER_ERROR";

export const DELETE_SUPPLIER_REQUEST = "DELETE_SUPPLIER_REQUEST";
export const DELETE_SUPPLIER_RESPONSE = "DELETE_SUPPLIER_RESPONSE";
export const DELETE_SUPPLIER_ERROR = "DELETE_SUPPLIER_ERROR";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";