export const GET_DETAILS_SUPPLIER_REQUEST = "GET_DETAILS_SUPPLIER_REQUEST";
export const GET_DETAILS_SUPPLIER_RESPONSE = "GET_DETAILS_SUPPLIER_RESPONSE";
export const GET_DETAILS_SUPPLIER_ERROR = "GET_DETAILS_SUPPLIER_ERROR";
