export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_RESPONSE = "CREATE_PRODCT_RESPONSE";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";

export const GET_ALL_CATEGORY_CREATED_RESPONSE =
  "GET_ALL_CATEGORY_CREATED_RESPONSE";
export const GET_ALL_CATEGORY_CREATED_REQUEST =
  "GET_ALL_CATEGORY_CREATED_REQUEST";
export const GET_ALL_CATEGORY_CREATED_ERROR = "GET_ALL_CATEGORY_CREATED_ERROR";

// export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST"
// export const GET_BRAND_RESPONSE = "GET_BRAND_RESPONSE"
// export const GET_BRAND_ERROR = "GET_BRAND_ERROR"

export const RESET = "RESET";
